export const PERFORM_SEARCH = "PERFORM_SEARCH";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_ERROR = "SEARCH_ERROR";
export const NEW_SEARCH = "NEW_SEARCH";

export const SHOW_GIPHY = "SHOW_GIPHY";
export const HIDE_GIPHY = "HIDE_GIPHY";

export const GET_RANDOM_GIPHY = "GET_RANDOM_GIPHY";
export const GET_RANDOM_GIPHY_SUCCESS = "GET_RANDOM_GIPHY_SUCCESS";
export const GET_RANDOM_GIPHY_ERROR = "GET_RANDOM_GIPHY_ERROR";
