export const GET_LOCATION = 'GET_LOCATION';

export const FETCH_WEATHER_BEGIN = 'FETCH_WEATHER_BEGIN';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAILURE = 'FETCH_WEATHER_FAILURE';

export const EXAMPLE = 'EXAMPLE';
export const EXAMPLE_INITIATE = 'EXAMPLE_INITIATE';
