export const CREATE_COMMENT = "CREATE_COMMENT";
export const EDIT_COMMENT = "EDIT_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const FETCH_SINGLE_COMMENT = "FETCH_SINGLE_COMMENT";
export const CHANGE_AUTH = "CHANGE_AUTH";
